import org.gradle.api.tasks.bundling.Jar
import org.gradle.kotlin.dsl.named
import org.springframework.boot.gradle.tasks.bundling.BootJar
import org.springframework.boot.gradle.tasks.run.BootRun

/*
 * This file was generated by the Gradle 'init' task.
 */
plugins {
    id("spring-common-conventions")
}

dependencies {
}

val applicationGroup: String = project.findProperty("application.group").toString()
val applicationGroupName: String = project.findProperty("application.group.name").toString()
val applicationName: String = project.findProperty("application.name").toString()
val applicationVersion: String = project.findProperty("application.version").toString()
//
val currentTaskName = project.gradle.startParameter.taskNames.firstOrNull()

// jar에 기본 Manifest 속성이 없습니다. 등 오류 방지
tasks.named<Jar>("jar") {
    enabled = false
}

tasks.named<BootJar>("bootJar") {
    enabled = true

    archiveBaseName = applicationName
    archiveVersion = applicationVersion
    archiveFileName = "$applicationGroupName-$applicationName-$applicationVersion.jar"

    if (currentTaskName == "bootJar" || currentTaskName == "jar") {
        exclude("**/application**-env.yml")
    }
}

tasks.named<BootRun>("bootRun") {
    enabled = true
}
